import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  products: [
    {
      // _id: '1',
      name: "20G Protain Oats",
      slug: "20G-Protain-Oats",
      category: "Shirts",
      image: "/products/1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      // _id: '2',
      name: "Fortune Refine Oil",
      slug: "Fortune-Refine-Oil",
      category: "Shirts",
      image: "/products/2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '3',
      name: "Agni Tata tea",
      slug: "Agni-Tata-tea",
      category: "Pants",
      image: "/products/3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      // _id: '4',
      name: "Tata Sampann daal",
      slug: "Tata-Sampann-daal",
      category: "Pants",
      image: "/products/4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '5',
      name: "Nuts Rajsun",
      slug: "nuts-rajsun",
      category: "Pants",
      image: "/products/5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '6',
      name: "Maggi Mega Pack",
      slug: "Maggi-Mega-Pack",
      category: "Pants",
      image: "/products/6.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '7',
      name: "Tomato Ketchup",
      slug: "tomato-ketchup",
      category: "Pants",
      image: "/products/7.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '8',
      name: "fortune Kachi Ghani",
      slug: "fortune-kachi-ghani",
      category: "Pants",
      image: "/products/8.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
